variables:
  DJANGO_SETTINGS_MODULE: core.settings


stages:
  - build
  - test
  - deploy

job-test:
  stage: test
  image: python
  script:
    - python --version
    - pip install coverage django==5 dj-database-url python-decouple
    - python -m unittest

job-coverage:
  stage: test
  image: python
  script:
    - python --version
    - pip install coverage django==5 dj-database-url python-decouple
    - coverage run -m unittest
    - coverage report
    - coverage html
    - mkdir -p public/
    - mv htmlcov public/coverage/
  artifacts:
    paths:
      - public/


build-image:
  stage: build
  image: docker:stable
  script:
    - docker build . -t $CI_REGISTRY_IMAGE
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker push $CI_REGISTRY_IMAGE
  services:
    - docker:dind

job-pydocs:
  stage: build
  image: python
  script:
    - python --version
    - python -m pydoc -w roleta
    - mkdir -p public/
    - mv roleta.html public/
  artifacts:
    paths:
      - public/

pages:
  stage: deploy
  script: 
    - mkdir -p public/
    - echo '<h1>GitLab Pages</h1>' > public/index.html
  artifacts:
    paths:
      - public/