# Generated by Django 5.0.1 on 2024-03-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='cover',
            field=models.ImageField(default='imagens/placeholder.webp', upload_to='imagens/'),
        ),
    ]
