# Generated by Django 5.0.1 on 2024-03-06 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_jogo_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogo',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='jogo',
            name='game_name',
        ),
    ]
