# Generated by Django 5.0.1 on 2024-03-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_jogo_cover_remove_jogo_game_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='cover',
            field=models.ImageField(default='imagens/placeholder.png', upload_to='imagens/'),
        ),
        migrations.AddField(
            model_name='jogo',
            name='game_name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
