# Generated by Django 5.0.1 on 2024-03-06 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_jogo_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
